### PR TITLE
Brand styling alignment

### PR DESCRIPTION
**Pull request by bigomega**
- [x] Navbar
- [x] Jumbotron header
- [x] Footer

### CODE REVIEW

**Comment by bigomega** [comment]
### Screenshot

image

**Comment by praveenselvam** [comment]
Fantastic work @bigomega.

I feel the footer can be improved a little bit in terms of alignment. Please refer screenshot below.

a9684206-0cac-11e6-8f01-3e460907c311

**Comment by praveenselvam** [comment]
Also @bigomega, we should have a better background image. The one that is there right now is not appropriate.

**Comment by praveenselvam** [comment]
👍

**Pull request merged**
